Adding program to find pangram
TheAlgorithms/Julia pull request #100
Opened 2021-10-21 05:49 UTC by Ihjass

A pangram is a sentence using every letter of the alphabet at least once.
![pangram-output](https://user-images.githubusercontent.com/44056715/138218813-6bbccb97-85c7-425d-a2c0-8b61f3b3a383.PNG)

2021-11-05 18:11 UTC, Panquesito7 submitted a review, later dismissed
Thanks! 🚀

2021-11-05 18:12 UTC, Panquesito7 commented on src/strings/pangram.jl
> +# Contributed by:- [Ihjass](https://github.com/Ihjass)
```suggestion
# Contributed by:- [Ihjass Thasbekha](https://github.com/Ihjass)
```

2021-11-05 18:13 UTC, Panquesito7 approved these changes

2021-11-05 21:14 UTC, Panquesito7 requested changes
I think you need to add your program in the tests folder as seen in other files https://github.com/TheAlgorithms/Julia/tree/main/test

2021-11-06 13:23 UTC, uncomfyhalomacro submitted a review, later dismissed
Thanks for the contribution! :D

2021-11-06 13:25 UTC, uncomfyhalomacro commented
@Ihjass pls do add test for it to pass the CI. thank you!!

2021-11-08 00:22 UTC, Panquesito7 requested changes
Looks like all the other [**checks**](https://github.com/TheAlgorithms/Julia/pull/100/checks) are failing 😅 could you please fix that?
Let us know if you need any help here or in our [**Discord server**](https://discord.gg/c7MnfGFGa6). 😃

2021-11-12 07:29 UTC, uncomfyhalomacro submitted a review, later dismissed

2021-11-12 07:39 UTC, uncomfyhalomacro approved these changes

2021-11-12 07:42 UTC, merged

2021-11-12 15:24 UTC, Panquesito7 reviewed
LGTM! Thanks for fixing that, @uncomfyhalomacro! 🚀