Adding word count program
TheAlgorithms/Julia pull request #101
Opened 2021-10-21 05:54 UTC by Ihjass

This is a program to print the count of words in the given sentence
![word_count_output](https://user-images.githubusercontent.com/44056715/138219598-d5afcb88-3644-4629-a517-fc972be78987.PNG)

2021-11-05 18:15 UTC, Panquesito7 requested changes
I think you need to add your program in the tests folder as seen in other files https://github.com/TheAlgorithms/Julia/tree/main/test

2021-11-05 18:15 UTC, Panquesito7 commented on src/strings/word_count.jl
> +Program to find word count in the given sentence. The program will return count with the word.A full description of the algorithm can be found on [exercism](https://exercism.org/tracks/julia/exercise
```suggestion
Program to find word count in the given sentence. The program will return count with the word.
A full description of the algorithm can be found on [exercism](https://exercism.org/tracks/julia/exercises/word-count)
```

2021-11-05 18:15 UTC, Panquesito7 commented on src/strings/word_count.jl
> +# Contributed by:- [Ihjass](https://github.com/Ihjass)
```suggestion
# Contributed by:- [Ihjass Thasbekha](https://github.com/Ihjass)
```

2021-11-07 16:45 UTC, Panquesito7 submitted a review, later dismissed
Looks like all the other [**checks**](https://github.com/TheAlgorithms/Julia/pull/101/checks) are failing 😅 could you please fix that?
Let us know if you need any help here or in our [**Discord server**](https://discord.gg/c7MnfGFGa6). 😃

2021-11-12 07:02 UTC, uncomfyhalomacro submitted a review, later dismissed
Seems you misplaced `input` instead of `sentence`

2021-11-12 07:19 UTC, uncomfyhalomacro approved these changes

2021-11-12 07:33 UTC, merged

2021-11-12 15:27 UTC, Panquesito7 reviewed
LGTM! Thanks for helping, @uncomfyhalomacro! 🚀