Adding Atbash Cipher Program
TheAlgorithms/Julia pull request #104
Opened 2021-11-18 13:54 UTC by Ihjass

2021-11-18 15:03 UTC, Panquesito7 requested changes
Hey there! Thank you for submitting a PR! 😄 Please add your algorithm file in `src/TheAlgorithms.jl`. You can check other merged PRs such as in PR #103. Let us know if you need any help here or in our [**Discord server**](https://discord.gg/c7MnfGFGa6). 😃

2021-11-18 16:24 UTC, Panquesito7 approved these changes
LGTM 🚀 Thank you for your contribution! 😄👍

2021-11-19 09:05 UTC, uncomfyhalomacro reviewed
@Ihjass Please check. Just a small change :slightly_smiling_face:

2021-11-19 09:05 UTC, uncomfyhalomacro commented on src/cipher/atbash.jl
> +  if part != ""
```suggestion
  if !isempty(part)

```

2021-11-19 13:39 UTC, uncomfyhalomacro approved these changes

2021-11-19 18:09 UTC, Panquesito7 approved these changes
Thanks for helping, @uncomfyhalomacro! 😄

2021-11-19 18:10 UTC, merged