Re-write of directory_writer in Julia
TheAlgorithms/Julia pull request #190
Opened 2023-10-04 05:02 UTC by ChrisO345

Wrote `directory_writer.jl` and changed `directory_writer.yml` to use this file to build directory, rather than using a python script.

2023-10-04 11:37 UTC, uncomfyhalomacro approved these changes, later dismissed

2024-01-15 20:46 UTC, Panquesito7 requested changes

2024-01-15 20:46 UTC, Panquesito7 commented on .github/workflows/directory_writer.yml
> +  #workflow_dispatch:
Please add `workflow_dispatch` again. This will allow us to run it whenever we want.
```suggestion
  workflow_dispatch:
```

2024-01-15 20:46 UTC, Panquesito7 commented on .github/workflows/directory_writer.yml
> +          version: 1.8
The repository itself is using Julia 1.9 now.
```suggestion
          version: 1.9
```

2024-01-15 20:46 UTC, Panquesito7 commented on scripts/directory_writer.jl
> +print_directory()
Missing an endline.
```suggestion
print_directory()

```

2024-01-15 20:46 UTC, Panquesito7 commented on .github/workflows/directory_writer.yml
> +          git push --force origin HEAD:$GITHUB_REF || true
This won't work as the `main` branch is protected. We need to create a pull request, and then merge it, just like the previous workflow.

2026-02-26 03:06 UTC, closed without merging