added verlet integration
TheAlgorithms/Julia pull request #51
Opened 2021-06-15 16:00 UTC by Ved-Mahajan

2021-06-15 16:14 UTC, Ved-Mahajan commented
This is really strange lol

It was working earlier

2021-06-15 19:56 UTC, Panquesito7 requested changes
👍 Good work.

2021-06-15 19:56 UTC, Panquesito7 commented on src/math/sieve_of_eratosthenes.jl
> +
```suggestion
```

2021-06-15 19:56 UTC, Panquesito7 commented on src/math/sieve_of_eratosthenes.jl
> +-https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes
```suggestion
-https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes

Contributed By:- [Ved Mahajan](https://github.com/Ved-Mahajan)
```

2021-06-15 19:56 UTC, Panquesito7 commented on src/math/verlet.jl
> +Contributed by: [Ved Mahajan](https://github.com/Ved-Mahajan)
```suggestion
Contributed By:- [Ved Mahajan](https://github.com/Ved-Mahajan)
```

2021-06-15 19:56 UTC, Panquesito7 commented on src/math/sieve_of_eratosthenes.jl
> +function eratosthenes(n)
Please add documentation for this function.

2021-06-15 19:56 UTC, Panquesito7 commented on test/math.jl
> +        @test eratosthenes(1) == Int64[] # No prime number less that 1, so it should return empty array.
```suggestion
        @test eratosthenes(1) == Int64[] # No prime number less than 1, so it should return an empty array.
```

2021-06-17 03:16 UTC, Panquesito7 commented on src/math/sieve_of_eratosthenes.jl
> +function eratosthenes(n)
This function is missing documentation. Please add documentation to the function.

2021-06-17 08:38 UTC, Ved-Mahajan commented
It seems that there is some mess on my side.

I am closing this PR and will make a new PR with all the stuff in place

2021-06-17 08:38 UTC, closed without merging