[Work in progress] added Fibonacci number generator procedures
TheAlgorithms/Julia pull request #53
Opened 2021-06-16 20:25 UTC by M-CS-ME

This file contains 3 procedures for generating Fibonacci numbers.

- the first one is recursive,
- the second one is iterative-recursive (tail-call),
- the last is iterative using a while loop.

2021-06-27 00:19 UTC, Azzaare commented
Thanks @M-CS-ME for the addition!

Could you add some tests in `test/math.jl`?

It is something we want to ask in the guideline for contribution, but unfortunately, we haven't written things yet.

2021-06-27 00:20 UTC, Panquesito7 requested changes

2021-06-27 00:20 UTC, Panquesito7 commented on src/math/fib.jl
> +Program for calculating the nth fibonacci number
Please add a source or Wikipedia link for algorithm explanation.
You can also add a link to your GitHub profile at the bottom like

```markdown
Contributed By:- [Your name](Link to your GitHub profile)
```

2021-06-27 00:20 UTC, Panquesito7 commented on src/math/fib.jl
> +function fib_rec(n)
Please add detailed function documentation (including parameters).

2021-06-27 00:20 UTC, Panquesito7 commented on src/math/fib.jl
> +function fib_rec_iter(n)
Same here (missing documentation).

2021-06-27 00:20 UTC, Panquesito7 commented on src/math/fib.jl
> +function fib_iter(n)
Same here (missing documentation).

2021-07-01 06:32 UTC, Azzaare commented
As we don't have answer from @M-CS-ME at the moment, this PR becomes low priority.

Documentation and tests are required. Will make it draft for now.

2021-08-08 04:26 UTC, uncomfyhalomacro commented
@M-CS-ME Hello. How is your progress of this PR? Sorry for the ping.

2021-08-11 04:21 UTC, Azzaare commented
This is almost two months old. I think we should close the PR (the branch is still alive anyway, and we can always resurrect the PR).

What do you think @uncomfyhalomacro @Panquesito7 ?

2021-08-11 06:26 UTC, closed without merging