Add anagrams in strings
TheAlgorithms/Julia pull request #55
Opened 2021-06-17 14:44 UTC by ReneganRonin

2021-06-17 19:09 UTC, Panquesito7 requested changes
Please fix the [Codecov](https://github.com/TheAlgorithms/Julia/pull/55/checks?check_run_id=2850291641) warnings.

2021-06-17 19:09 UTC, Panquesito7 commented on src/strings/detect_anagrams.jl
> +is an anagram or not of a subject word.
Please add a Wikipedia reference of this algorithm.

2021-06-17 19:09 UTC, Panquesito7 commented on src/strings/detect_anagrams.jl
> +is an anagram or not of a subject word.
```suggestion
is an anagram or not of a subject word.

Contributed By:- [Soc V. E.](https://github.com/ReneganRonin)
```

2021-06-17 19:09 UTC, Panquesito7 commented on src/strings/detect_anagrams.jl
> +function detect_anagrams(subject, candidates)
Please add documentation for this function (see, for example, the [`knapsack`](https://github.com/TheAlgorithms/Julia/blob/main/src/knapsack/knapsack.jl) problem).

2021-06-18 04:50 UTC, Panquesito7 reviewed
Almos there! 😄

2021-06-18 04:50 UTC, Panquesito7 commented on src/strings/detect_anagrams.jl
> +
```suggestion
```

2021-06-18 04:50 UTC, Panquesito7 commented on src/strings/detect_anagrams.jl
> +Inspired by the Extreme Startup game https://github.com/rchatley/extreme_startup
```suggestion
Inspired by the [Extreme Startup game](https://github.com/rchatley/extreme_startup)
```

2021-06-18 04:50 UTC, Panquesito7 commented on src/strings/detect_anagrams.jl
> +is an anagram or not of a subject word.
Could you please add documentation for the function parameters?

2021-06-18 04:50 UTC, Panquesito7 commented on src/strings/detect_anagrams.jl
> +is an anagram or not of a subject word.
```suggestion
is an [Anagram](https://en.wikipedia.org/wiki/Anagram) or not of a subject word.
```

2021-06-18 21:30 UTC, Panquesito7 approved these changes
LGTM. Thank you for your contribution! 👍 🎉

2021-06-18 21:31 UTC, Panquesito7 commented
@arubhardwaj, or @Azzaare, could you please do the code review? Thanks. 🙂

2021-06-23 17:42 UTC, arubhardwaj requested changes
Some CIs are conflicting, please resolve them!

2021-06-27 02:39 UTC, Panquesito7 reviewed
Any reasons why the [Codecov](https://github.com/TheAlgorithms/Julia/pull/55/checks?check_run_id=2923303166) checks are failing? @Azzaare @arubhardwaj.

2021-06-27 03:28 UTC, Azzaare commented
I don't have time to check now, but my guess is that some part of the code are not covered by the test, thus decreasing the coverage.
Coverage bug might occur for some inline functions, but we can make the code coverage tool a bit more lenient.

For now, we can probably merge current PRs that succeed on CI build but not on coverage.

Once again, as long as we don't provide solid contribution guidelines (and we're late because of me ><) we should be kind of lenient

2021-06-28 02:51 UTC, Azzaare approved these changes

2021-06-28 02:54 UTC, Azzaare requested changes
@ReneganRonin you forgot to add the string test file in runtests.jl. Could you take care of it?

2021-06-28 03:16 UTC, Azzaare commented
@ReneganRonin you're in for debugging now :p

2021-06-28 04:55 UTC, ReneganRonin commented
@Panquesito7 Codecov issue fixed. it seems to be an issue from `is_palindrome` so i fixed it.

2021-06-28 05:03 UTC, Azzaare commented
Thanks! Will try to merge things as soon as I am in front of a computer!

2021-06-28 06:48 UTC, Azzaare submitted a review, later dismissed
Good to go

2021-06-28 11:00 UTC, ReneganRonin commented
lol 😂 i didnt notice i add the commit verlet integration when i was doing demonstration for Ved. going to rebase and drop them lol

2021-07-01 06:23 UTC, Azzaare approved these changes

2021-07-01 06:23 UTC, merged